// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateJob(arg1) {
  return window['go']['main']['App']['CreateJob'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['main']['App']['DeleteJob'](arg1);
}

export function GetJob(arg1) {
  return window['go']['main']['App']['GetJob'](arg1);
}

export function GetJobs() {
  return window['go']['main']['App']['GetJobs']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateJob(arg1) {
  return window['go']['main']['App']['UpdateJob'](arg1);
}
