// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function CreateJob(arg1:db.Job):Promise<db.Job>;

export function DeleteJob(arg1:string):Promise<void>;

export function GetJob(arg1:string):Promise<db.Job>;

export function GetJobs():Promise<Array<db.Job>>;

export function Greet(arg1:string):Promise<string>;

export function UpdateJob(arg1:db.Job):Promise<db.Job>;
